// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentACarApi.Data;

#nullable disable

namespace RentACarApi.Data.Migrations
{
    [DbContext(typeof(RentACarContext))]
    [Migration("20250305102528_SupportMessage")]
    partial class SupportMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RentACarApi.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("int");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<int>("Km")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("PricePerKm")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("ModelId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A Volkswagen Passat egy tágas és kényelmes szedán, ideális hosszabb utakra és városi közlekedésre egyaránt. Gazdaságos fogyasztás, modern technológia és megbízható teljesítmény jellemzi. Automata váltóval, klímával és tágas csomagtérrel rendelkezik, tökéletes választás üzleti és családi utakhoz.",
                            FuelTypeId = 1,
                            HorsePower = 150,
                            Km = 121322,
                            ModelId = 3,
                            PricePerKm = 50,
                            Year = 2016
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "A Ford Focus egy dinamikus és megbízható kompakt autó, amely ideális választás városi közlekedéshez és hosszabb utakhoz egyaránt. Alacsony fogyasztás, kényelmes utastér és modern biztonsági felszereltség jellemzi.",
                            FuelTypeId = 2,
                            HorsePower = 120,
                            Km = 98500,
                            ModelId = 4,
                            PricePerKm = 45,
                            Year = 2018
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "A Toyota Corolla egy legendásan tartós és gazdaságos modell, amely kiváló vezetési élményt nyújt. Kényelmes beltér, megbízható motor és alacsony fenntartási költségek teszik népszerűvé.",
                            FuelTypeId = 1,
                            HorsePower = 132,
                            Km = 75000,
                            ModelId = 5,
                            PricePerKm = 48,
                            Year = 2020
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "A Mercedes E-Osztály egy elegáns és tágas prémium szedán, amely kimagasló komfortot és technológiai innovációt kínál. Automata váltó, bőr belső és fejlett vezetéstámogató rendszerek biztosítják a luxus élményt.",
                            FuelTypeId = 2,
                            HorsePower = 190,
                            Km = 105000,
                            ModelId = 2,
                            PricePerKm = 80,
                            Year = 2017
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "A Mercedes C-Osztály sportos megjelenése és erőteljes motorja garantálja a dinamikus vezetési élményt. Kiváló gyorsulás, prémium belső tér és modern technológia jellemzi.",
                            FuelTypeId = 1,
                            HorsePower = 204,
                            Km = 60200,
                            ModelId = 1,
                            PricePerKm = 100,
                            Year = 2019
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "A Toyota Corolla hibrid változata környezetbarát és takarékos megoldást kínál azok számára, akik modern és hatékony autót keresnek. Csendes üzemmód, alacsony fogyasztás és megbízható teljesítmény jellemzi.",
                            FuelTypeId = 3,
                            HorsePower = 180,
                            Km = 50000,
                            ModelId = 5,
                            PricePerKm = 90,
                            Year = 2021
                        });
                });

            modelBuilder.Entity("RentACarApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hétköznapi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Luxus"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sport"
                        });
                });

            modelBuilder.Entity("RentACarApi.Models.FuelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Benzin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dízel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Benzin-Hibrid"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dízel-Hibrid"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Elektromos"
                        });
                });

            modelBuilder.Entity("RentACarApi.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Toyota"
                        });
                });

            modelBuilder.Entity("RentACarApi.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManufacturerId = 1,
                            Name = "C-Osztály"
                        },
                        new
                        {
                            Id = 2,
                            ManufacturerId = 1,
                            Name = "E-Osztály"
                        },
                        new
                        {
                            Id = 3,
                            ManufacturerId = 3,
                            Name = "Passat"
                        },
                        new
                        {
                            Id = 4,
                            ManufacturerId = 5,
                            Name = "Focus"
                        },
                        new
                        {
                            Id = 5,
                            ManufacturerId = 6,
                            Name = "Corolla"
                        });
                });

            modelBuilder.Entity("RentACarApi.Models.Car", b =>
                {
                    b.HasOne("RentACarApi.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentACarApi.Models.FuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentACarApi.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FuelType");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("RentACarApi.Models.Model", b =>
                {
                    b.HasOne("RentACarApi.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });
#pragma warning restore 612, 618
        }
    }
}
